services:
  # Backend Web Service
  - type: web
    name: bestill-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  # Frontend Static Site
  - type: static
    name: bestill-frontend
    buildCommand: echo "Static site ready"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
